# Модуль Numpy  

In [3]:
print("Hello, Jupyter")

Hello, Jupyter


In [4]:
#установка Numpy
!pip install numpy

In [9]:
#импортирование модуля (библиотеками, фреймворки)
import numpy as np 

- создание массивов


In [10]:
# создание вектор-строки (1-мерный массив) из строки 
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [11]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [13]:
# создание массива (вектор-строки) из нулей
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# создание вектор-столбца из нулей
# количество строк, количество столбцов и т.д.)
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [16]:
# создание матрицы из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# метод, который создает вектор-строку со значениями из линейной последовательности
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [20]:
# вектор-строка со значениями из равномерного распределения
# например, от 0 до 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [25]:
# случайные значения из равномерного распределения от 0 до 1
np.random.random((3,3))

array([[0.60522668, 0.38479662, 0.76026661],
       [0.03730595, 0.10403962, 0.81590215],
       [0.85449354, 0.33752868, 0.71184008]])

In [27]:
# случайные целые значения
# случайное число
np.random.randint(10)

5

In [28]:
np.random.randint(10, size=5)

array([2, 3, 7, 3, 9])

In [30]:
# матрица формой 2 на 3 со случ. знач. от 10 до 20
np.random.randint(10, 20, size=(2,3))

array([[16, 17, 18],
       [12, 18, 16]])

- атрибуты

In [33]:
a = np.random.randint(10, size=(3,5))
a

array([[9, 7, 3, 4, 5],
       [8, 8, 4, 9, 6],
       [7, 7, 9, 8, 4]])

# размерность массива - кол-во измерений/осей
a.ndim

In [35]:
# форма массива
a.shape

(3, 5)

In [36]:
# количество всех элементов массива
a.size

15

In [37]:
# тип значений массива
a.dtype


dtype('int32')

In [40]:
# a.astype("float16")

- индексация


In [1]:
import numpy as np

In [3]:
a2 = np.random.randint(10, size=10)
a2

array([3, 0, 4, 6, 2, 7, 2, 3, 3, 6])

In [5]:
# чтение значений 
a2[0]

3

In [6]:
a2[-1]

6

In [9]:
# изменение значений 
a2[1]=10
a2

array([ 3, 10,  4,  6,  2,  7,  2,  3,  3,  6])

In [11]:
a3 = np.random.randint(10, size=(3, 5))
a3

array([[8, 7, 2, 8, 1],
       [2, 6, 4, 9, 0],
       [0, 3, 0, 8, 0]])

In [12]:
# стандартный питоновский способо
a3[0][2]

2

#способ Numpy
# [индекс строк, индекс столбца]
a3[0, 2]

- срезы

In [16]:
# срез по строкам
a3[1:]

array([[2, 6, 4, 9, 0],
       [0, 3, 0, 8, 0]])

In [18]:
# срез по строкам от 1 индекса до конца
# срез по столбцам от начала до 3 индекса не включительно
3[1:, :3]

array([[2, 6, 4],
       [0, 3, 0]])

-  представления (views) и копии (copies)


In [20]:
# списjr
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [23]:
# вектор-строкf
my_arr = np.array(my_list)
my_arr

array([1, 2, 3, 4, 5])

In [24]:
# срез списка
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [27]:
# срез вектор-строки
sub_arr = my_arr[2:]
sub_arr

array([3, 4, 5])

In [28]:
sub_list[0] = 100
my_list

[1, 2, 3, 4, 5]

In [30]:
# массив, созданный срезом другого массива является т.н. представлением 
# поэтому, изменения в массиве-представлении отражаются на исходный массив
sub_arr[0] = 1000
my_arr

array([   1,    2, 1000,    4,    5])

In [31]:
# копия массива
copy_arr = my_arr[:2].copy()
copy_arr

array([1, 2])

In [33]:
copy_arr[0] = 10
my_arr

array([   1,    2, 1000,    4,    5])

- изменение формы


In [34]:
# 1-мерный массив (вектор-строка)
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr.shape


(9,)

In [36]:
# изменение формы - создание вектор-столбца
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- универсальные функции

In [42]:
a = np.array([1,2,3,4,5])
b = np.array([20,30,40,50,60])
print(a)
print(b)

[1 2 3 4 5]
[20 30 40 50 60]


In [43]:
# поэлементное деление
a /b 

array([0.05      , 0.06666667, 0.075     , 0.08      , 0.08333333])

In [44]:
a / 100


array([0.01, 0.02, 0.03, 0.04, 0.05])

In [45]:
100 / a


array([100.        ,  50.        ,  33.33333333,  25.        ,
        20.        ])

In [46]:
a > b


array([False, False, False, False, False])

- агрегирование


In [50]:
# агрегирование - вычисление неких сводных показателей 
arr_2 = np.random.random(10)
arr_2

array([0.78859514, 0.83207533, 0.07274358, 0.73737793, 0.88417195,
       0.95691918, 0.9465926 , 0.75478683, 0.33871564, 0.00874075])

In [51]:
# сумма 
np.sum(arr_2)


6.320718944522832

In [52]:
# минимум 
np.min(arr_2)

0.008740754070207246

In [54]:
# среднее арифметическое
np.mean(arr_2)

0.6320718944522832

- маскирование

In [55]:
# извлечение значений, которые отвечают некоторому условию 
x = np.random.randint(10, size=7)
x

array([3, 8, 8, 0, 6, 4, 7])

In [56]:
x < 5

array([ True, False, False,  True, False,  True, False])

In [57]:
x[x<5]

array([3, 0, 4])

In [60]:
# только те значения, которые меньше 5
x[x<5] = 0
x

array([0, 8, 8, 0, 6, 0, 7])

- "прихотливая" индексация

In [63]:
# прихотливая индексация - выбор значений по определенным индексам
x = np.random.randint(10, size=7)
x

array([6, 1, 6, 0, 0, 8, 2])

In [66]:
# 
x[[5,0,3]]

array([8, 6, 0])

In [68]:
# выбор значений по массиву с индексами, который находится в переменной indices
indices = np.array([5,0,3])
x[indices]

array([8, 6, 0])

In [70]:
x2 = np.random.randint(10, size=(3,5))
x2

array([[7, 7, 7, 3, 6],
       [9, 6, 4, 4, 7],
       [8, 9, 8, 3, 6]])

In [72]:
# сочетание среза и прихотливой индексации
x2[1:, [2,0]]

array([[4, 9],
       [8, 8]])

In [73]:
x2 < 5

array([[False, False, False,  True, False],
       [False, False,  True,  True, False],
       [False, False, False,  True, False]])

In [77]:
# сочетание маскирования и прихотливой индексации
x2[x2 > 5][[5,0,3]]

array([6, 7, 6])